spring:
    profiles: dev
    data:
        mongodb:
            host: localhost
            port: 27017
            database: linguodb
    servlet:
        multipart:
            enabled: true
            max-file-size: 500MB
            file-size-threshold: 4KB

linguo:
    admin: linguo-admin
    password: linguo-secret
    
server:
    port: 9090
    
    
---

spring:
    profiles: prod
    data:
        mongodb:
            host: ${DB_HOST}
            port: ${DB_PORT}
            database: ${DB}
            username: ${DB_USER}
            password: ${DB_PASS}
    servlet:
        multipart:
            enabled: true
            max-file-size: 500MB
            file-size-threshold: 4KB
            
linguo:
    admin: ${ADMIN}
    password: ${PASSWORD}
    
server:
    port: ${PORT}